### ISSUE TITLE
Upgrade to nexus 3.3.1

### ISSUE THREAD

**Issue by xyloman** [making/nexus-boshrelease#1]
Upgrade to nexus 3.3.1: https://support.sonatype.com/hc/en-us/articles/115006333387-Nexus-Repository-Manager-3-3-1-Release-Notes

Not a lot of new features but personally I have found the bosh release to be much easier to use for the management of our nexus oss server over performing the work by hand.

**Comment by making** [comment]
@xyloman  I've released nexux-boshrelease 0.1.0 which includes nexus 3.3.2.
Please try it.
https://github.com/making/nexus-boshrelease/releases/tag/0.1.0

**Comment by xyloman** [comment]
@making thank you, worked perfectly.
