### ISSUE TITLE
Post start script assumes that ssl termination is done on the nexus host.

### ISSUE THREAD

**Issue by arthomps** [making/nexus-boshrelease#11]
Good Afternoon,

I upgraded to 0.6.0 version the other day and bosh hangs when running the post-start scripts.   The logs are essentially

"Waiting until HTTPS is ready .."

I believe the issue is on the below line:

https://github.com/making/nexus-boshrelease/blob/1a1310c40712e235ca9e1456393e55b38dcd02d7/jobs/nexus/templates/post-start.erb#L7

Where it calls https://localhost.  If you're doing ssl term at the lb - that command hangs indefinitely as it does in my case.  

In the short term, I suspect putting ssh_only=true back in the config properties might resolve the symptom for me.  I haven't tested, because i suspect that it will introduce different problems - for example the change admin password likely has the same issue.

**Comment by arthomps** [comment]
This is likely a duplicated of #10

**Comment by making** [comment]
Setting ssl_cert, ssl_key will work as a workaround.

**Comment by making** [comment]
fixed by https://github.com/making/nexus-boshrelease/commit/f0dc14d260464a2d62285dc2d81f2ff533556b7d

**Comment by making** [comment]
Can you please update to 0.7.0?
https://github.com/making/nexus-boshrelease/releases/tag/0.7.0

**Comment by arthomps** [comment]
works perfectly.  sorry for my slow response.
