### ISSUE TITLE
Upgrade Bosh release to Nexus 3.12 for Native S3 Blob Store Support

### ISSUE THREAD

**Issue by ghost** [making/nexus-boshrelease#14]
Could you kindly update the bosh release to the latest version of Nexus OSS 3.12, which now has native support for Amazon S3 for blob storage? Thanks for your efforts. 

https://help.sonatype.com/repomanager3/release-notes/2018-release-notes#id-2018ReleaseNotes-RepositoryManager3.12.0

**Comment by making** [comment]
That's a great news!
I'll update today.
Thank you for letting me know.

**Comment by making** [comment]
Fixed via 68c46a02b0923b22e1ca448fd329bcad09e50cb8
