### ISSUE TITLE
Update Release to Nexus 3.12.1 (Critical Bug Fix) 

### ISSUE THREAD

**Issue by ghost** [making/nexus-boshrelease#16]
Please update the nexus bosh release to v3.12.1 to address a critical bug fix that is impacting the upload of artifacts to nexus. 

https://help.sonatype.com/repomanager3/release-notes/2018-release-notes#id-2018ReleaseNotes-RepositoryManager3.12.1

**Comment by making** [comment]
0.10.1 has been released
