### ISSUE TITLE
Update to 3.14.0 (CVE Fixes)

### ISSUE THREAD

**Issue by arthomps** [making/nexus-boshrelease#17]
Good Morning,

Any chance of an updated release in the near future?  3.13 and 3.14 have come out.  The last of which includes some CVEs.  

https://help.sonatype.com/repomanager3/release-notes/2018-release-notes#id-2018ReleaseNotes-RepositoryManager3.14.0

**Comment by making** [comment]
It should be updated soon but not passing tests in concourse yet.

**Comment by making** [comment]
@arthomps Released
https://github.com/making/nexus-boshrelease/releases/tag/0.12.0

**Comment by arthomps** [comment]
works perfectly.  thank you.
