### ISSUE TITLE
ctl script takes too long to complete, causing monit to start multiple processes

### ISSUE THREAD

**Issue by kansberry** [making/nexus-boshrelease#18]
We are currently using nexus version 0.12.0. When starting nexus, "chown" command against the "DATA_DIR" is taking roughly 8 minutes to complete due to the number of files in the /var/vcap/store/sonatype-work/nexus3/blobs folder, which contains 261617 files. Our idea would be to change https://github.com/making/nexus-boshrelease/blob/master/jobs/nexus/templates/ctl.erb#L39, so that we only run "chown" again files that are not owned by "vcap".

**Comment by making** [comment]
Could you please send a pull request?
