### ISSUE TITLE
Bump to 3.6.x

### ISSUE THREAD

**Issue by jgprogramming** [making/nexus-boshrelease#9]
Hey, are there any plans of updating nexus to 3.6.x? We could really use new docker authentication.

**Comment by making** [comment]
Will do soon, thanks!

iPhoneから送信

2017/10/18 16:14、Jakub Grześka <notifications@github.com> のメッセージ:

**Comment by making** [comment]
@jgprogramming Released nexus-boshrelease 0.5.0 that supports nexus 3.6
